name: Documentation Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README
      run: |
        if [ ! -s README.md ]; then
          echo "README.md is empty or missing"
          exit 1
        fi
        echo "README.md check passed"
    
    - name: Check Documentation Structure
      run: |
        required_files=(
          "01_documentation/README.md"
          "04_processed_data/duckdb/README.md"
          "LICENSE"
          "CONTRIBUTING.md"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Required documentation file missing: $file"
            exit 1
          fi
        done
        
        echo "Documentation structure check passed"
    
    - name: Check File Sizes
      run: |
        # Check for large files that shouldn't be in repo
        large_files=$(find . -type f -size +50M -not -path "./.git/*" | head -10)
        if [ ! -z "$large_files" ]; then
          echo "Warning: Large files found:"
          echo "$large_files"
          echo "Consider adding these to .gitignore"
        fi 